### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by Thommond** [kevinlueke/kevinlueke.github.io#1]
https://github.com/kevinlueke/kevinlueke.github.io/blob/98ee9e3db1be29ba429893c08dd8539ce73e7958/resume/resume.html#L15

**Comment by kevinlueke** [comment]
Working on fixing it now

**Comment by zachfedor** [comment]
Okay, @Thommond I spoke too soon. It looks like this link is not broken at all. I misread which link you were talking about. Can you let us know what you meant?
